### ISSUE TITLE
Support for newest storefront version

### ISSUE THREAD

**Issue by haukebri** [Agence-DnD/vue-storefront-prismic-connector#1]
## Current behavior
The frontend is not able to compile with the current version of vuestorefront

## Steps to reproduce the issue
- Copy the connector to the newest version of the vuestorefront.
- Install dependencies, start dev server
--> Javascript error due to several dependency changes and Search adapter changed

I successfully resolved the dependency issues but get an error within the store mechanic.

**Comment by Dnd-Gimix** [comment]
Hello @haukebri ,

Thank you for your interest in our PRISMIC connector.
We have acknowledged your issue and we will provide a compatibility upgrade as soon as possible for the latest Vue Storefront version.

Regards,

**Comment by Jensderond** [comment]
Hi @Dnd-Gimix,
What is the status of this issue?

**Comment by Dnd-Gimix** [comment]
Hello @Jensderond ,

Thank you very much for contributing to VSF - Prismic connector !
We will test your contribution and integrate it if everything is OK ;)

We will come back to you.
Have a good day !

Regards,

**Comment by Jensderond** [comment]
Hi @Dnd-Gimix , any updates on this?

**Comment by Dnd-Gimix** [comment]
Hello @Jensderond ,

Unfortunately, we haven't been able to check your contribution yet.
I will keep you informed when it is the case.

Have a nice day !
Regards,

**Comment by Dnd-Gimix** [comment]
Hello @Jensderond ,

Thanks again, your PR has been merged.

Regards
